### ISSUE TITLE
Problem with my clang library path ?

### ISSUE THREAD

**Issue by Goles** [Rip-Rip/clang_complete#222]
Hey I'm getting the following error when I open an `Objective-C` file.

```
Error detected while processing function <SNR>23_ClangCompleteInit..<SNR>23_initClangCompletePython:
line    8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/goles/.vim/bundle/clang_complete/plugin/libclang.py", line 11, in initClangComplete
    Config.set_library_path(library_path)
  File "/Users/goles/.vim/plugin/clang/cindex.py", line 2999, in set_library_path
    raise Exception("library path must be set before before using " \
Exception: library path must be set before before using any other functionalities in libclang.
```

I'm already (as far as I know ) specifying where my library is located via

``` vimL
let g:clang_library_path ='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib'
```

Any ideas of what could be going on here?

**Comment by itlodge** [comment]
@Rip-Rip , Thank you very much!
