### ISSUE TITLE
Quotation marks problems

### ISSUE THREAD

**Issue by krzbe** [Rip-Rip/clang_complete#270]
Hello, 

I have two problems with quotation marks in cpp code, when using clang-complete:
First: when quick-fix will find warning exactly on quotation mark, inside function call, whole file after that place will be marked as string content (syntax highlighting is broken there), for example:

``` cpp
void test(char * x)     
{

}

void function()
{

    char * str = "str";
    int y=23;

    test("some text");
    test("other text");
    int x=10;
    //comment here

}

```

After that, code completion is not working anymore (until I fix the code).

Second issue: when I leave " sign alone, quick-fix will throw exception (maybe output from clang should be escaped?):

```
Error detected while processing function g:ClangUpdateQuickFix..<SNR>16_DoPeriodicQuickFix..<SNR>16_ClangQuickFix:
line    8:
E722: Missing comma in Dictionary: "\' character', 'type': 'W', 'col': 5, 'bufnr': 1}, {'lnum': 12, 'text': 'expected expression', 'type': 'E', 'col': 5, 'bufnr': 1}, {'lnum': 14, 'text': "conversion from string literal to 'char *' is d
eprecated", 'type': 'W', 'col': 10, 'bufnr': 1}]
E15: Invalid expression: [{'lnum': 9, 'text': "conversion from string literal to 'char *' is deprecated", 'type': 'W', 'col': 18, 'bufnr': 1}, {'lnum': 12, 'text': 'missing terminating \'"\' character', 'type': 'W', 'col': 5, 'bufnr': 1
}, {'lnum': 12, 'text': 'expected expression', 'type': 'E', 'col': 5, 'bufnr': 1}, {'lnum': 14, 'text': "conversion from string literal to 'char *' is deprecated", 'type': 'W', 'col': 10, 'bufnr': 1}]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
vim.error
line   27:
E121: Undefined variable: l:list
E116: Invalid arguments for function setqflist
```

It is somehow connected with warning/error reporting.

Tested with clang-3.3-svn.

**Comment by mlen** [comment]
I'm using latest clang_complete with clang 4.0 and I'm hitting the second issue. Probably there was some regression since the time it was fixed
```
Error detected while processing function <SNR>40_DoPeriodicQuickFix[8]..<SNR>40_ClangQuickFix:        
line    5:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>40_DoPeriodicQuickFix[8]..<SNR>40_ClangQuickFix:
line    5:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>40_DoPeriodicQuickFix[8]..<SNR>40_ClangQuickFix:
line    5:
vim.error: Vim(let):E722: Missing comma in Dictionary: "\' character', 'type': 'W', 'col': 5, 'bufnr': 1},
 {'lnum': 35, 'text': 'expected expression', 'type': 'E', 'col': 5, 'bufnr': 1}]
```

**Comment by mlen** [comment]
Another solution (that doesn't require pyeval): https://github.com/Rip-Rip/clang_complete/pull/524
