### ISSUE TITLE
Loading libclang failed, completion won't be available

### ISSUE THREAD

**Issue by PetrusZ** [Rip-Rip/clang_complete#370]
It works befofe, but after I updated something, like updating ubuntu to 13.10 and some others, vim shows:

```
Loading libclang failed, completion won't be available
Consider setting g:clang_library_path
Loading libclang failed, completion won't be available
Consider setting g:clang_library_path
Loading libclang failed, completion won't be available
Consider setting g:clang_library_path
```

I find libclang.so in "/usr/lib/llvm-3.2/lib/libclang.so", so I set "let g:clang_library_path='/usr/lib/llvm-3.2/lib' ".

But this time:

```
handle function <SNR>17_ClangCompleteInit..<SNR>17_initClangCompletePython error occurs:
line 29:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/silence/.vim/bundle/clang_complete/plugin/libclang.py", line 61, in initClangComplete
    Config.set_library_path(library_path)
  File "/home/silence/.vim/bundle/vundle/plugin/clang/cindex.py", line 3093, in set_library_path
    raise Exception("library path must be set before before using " \
Exception: library path must be set before before using any other functionalities in libclang.
line 30:
E121: Undefined variable: l:res
E15: Invalid expression: l:res == 0
```

**Comment by bendaojiu** [comment]
But how it works ? I set my g:clang_library_path. It don't work.
