### ISSUE TITLE
SIGSEGV using clang_complete

### ISSUE THREAD

**Issue by trombonehero** [Rip-Rip/clang_complete#446]
Hi,

My Vim has been crashing lately when I type the C++ name resolution operator (`::`):

```
Vim: Caught deadly signal SEGV
Vim: preserving files...

Error detected while processing function ClangComplete:Vim: Finished.

line   22:
Exception KeyError: KeyError(34599219200,) in <module 'threading' from '/usr/local/lib/python2.7/threading.pyc'> ignoredTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/home/jon/.vim/bundle/clang_complete/plugin/libclang.py", line 466, in getCurrentCompletions
    cancel = int(vim.eval('complete_check()'))
AttributeError: 'NoneType' object has no attribute 'eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'command'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'registerEvent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'finish'

clang_complete: completion time 0.239590
line   40:
E121: Undefined variable: l:res
E15: Invalid expression: l:res
```

I'm using Clang 3.4.1 on FreeBSD 10.1.

**Comment by battlesnake** [comment]
I recently got this too, when opening files

`2 files to edit
Vim: Caught deadly signal SEGV

Exception KeyError: KeyError(140283346540288,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignoredVim: Finished.

Segmentation fault (core dumped)`

I'm doing some nasty TMP hackery though so I'm not surprised - if it keeps crashing after I've tidied the code, I'll make a MWE and post it

**Comment by wrachwal** [comment]
It crashes regularly... (Vim 7.4 + libclang 3.6 from Ubuntu 14.04)

```
Press ENTER or type command to continueVim: Caught deadly signal SEGV
Error detected while processing function ClangComplete:Vim: Finished.

line   22:
Exception KeyError: KeyError(140683960645376,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignoredTraceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/valdi/config/vimfiles/bundle/clang_complete/plugin/libclang.py", line 484, in getCurrentCompletions
cancel = int(vim.eval('complete_check()'))
AttributeError: 'NoneType' object has no attribute 'eval'
Traceback (most recent call last):
File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'command'
Traceback (most recent call last):
File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'registerEvent'
Traceback (most recent call last):
File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'finish'

line   50:
E121: Undefined variable: l:res
E15: Invalid expression: l:res
E840: Completion function deleted text
```

in my ~/.vimrc
```
" XXX: libclang.so.1 is not recognized. I had to symlink libclang.so to it!
let g:clang_library_path = "/usr/lib/x86_64-linux-gnu/"
let g:clang_snippets = 1
let g:clang_snippets_engine = 'clang_complete'
set completeopt=menu,longest
```

**Comment by wilywampa** [comment]
I'm getting the same error when I work with large files/projects. I believe it's related to https://github.com/Rip-Rip/clang_complete/pull/102 in that it's probably also caused by Vim's Python interface not being thread-safe. I don't even know where to start debugging it.

**Comment by felixendres** [comment]
Same here, I guess. First time though, since about a year. Ubuntu 14.04 with VIM 7.4 (2013 Aug 10, compiled Nov 24 2016 16:42:52) using /usr/lib/x86_64-linux-gnu/libclang-3.4.so.1
```
Vim: Caught deadly signal SEGV
Vim: preserving files...

Fehler beim Ausführen von "function ClangComplete":Vim: Finished.

Zeile   22:
Exception KeyError: KeyError(139792440358656,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignoredTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/endres/.vim/plugin/libclang.py", line 484, in getCurrentCompletions
    cancel = int(vim.eval('complete_check()'))
AttributeError: 'NoneType' object has no attribute 'eval'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'command'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'registerEvent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'finish'

clang_complete: completion time 0.027561
Zeile   50:
E121: Undefinierte Variable: l:res
E15: ungültiger Ausdruck: l:res
E840: Text durch Vervollständigungsfunktion gelöscht-- Benutzerdefinierte Ergänzung (^U^N^P) Muster nicht gefunden13;123M1;125M                    2;125M 3;127M                           4;125M 5;125M    6;125M 7;127M                                               8;127M 9;129M                      

                                                               
                                                                                           10;129M                                    
                                                                                                                                        
                                                                                                                                                                11;127M 12;127M     
                                                                                                                                                                                                           
                                                                                                                                                                                                            
                                                                                                                                                                                                                                       13;127M                                                  100H14;127M                       
                                                                                      
                                                                                                                 15;125M 18;125M                           
                                                                                                                                                                               19;125M                                 
                                                                                                                                                                                                                         
                                                                                                                                                                                                                                          20;125M                  
                        
                                 21;125M 22;127M                                            
                                                                                              
                                                                                                               23;127M                                                      24;125M 26;125M                                                        27;125M                                         28;125M                                                        30;123M 32;123M    
                                                                                                                                                                    33;123M 34;125M                           
                                                                                                                                                                                                                                  35;125M                     36;125M                   37;125M 38;127M                 
                                                                              39;127M                            40;127M                           41;125M 42;125M                        43;123M 46;123M                        
                                                                                                                                                                                                                                                                  47;123M 48;125M                   
                                                                                  49;125M                           
                                                                                                                                        50;125M      
                                                                                                                                                                                           51;123M 53;123M           
                                                                                                                                                                                                                                                               54;123M 55;125M                   
                                                                               56;125M                           
                                                                                                                                     57;125M                                    
                                                                                                                                                                                  
                                                                                                                                                                                            58;125M      
                                                                                                                                                                                                                                             59;144M                                                                60;123M 61;224M 13;123M

```

**Comment by thecloudexpanse** [comment]
I've been running into the same repeatable crash on [s]OS X[/s] macOS. Wrapping exception handling around the failing line in libclang.py seems to have fixed the Vim crash. It still prints 'libclang: crash detected in code completion' to the console, but now catches the exception so Vim doesn't die and take my unsaved work with it.

493   while t.isAlive():
494     t.join(0.01)
495     cancel = 0
496     try:
497       cancel = int(vim.eval('complete_check()'))
498     except:
499       cancel = 1
500     if cancel != 0:
501       return (str([]), timer)

**Comment by iiey** [comment]
Same here:

```sh
Vim: Caught deadly signal SEGV
Vim: preserving files...
Error detected while processing function ClangComplete:Vim: Finished.

line   22:
Exception KeyError: KeyError(139648420820736,) in <module 'threading' from '/usr/lib/python3.2/threading.py'> ignored
```
clang_complete HEAD
VIM - Vi IMproved 8.0
Ubuntu 12.04
libclang.so.3.9

**Comment by thecloudexpanse** [comment]
I finally just had to disable completions (in libclang.py, getCurrentCompletions method) with this:

`    timer = CodeCompleteTimer(debug, vim.current.buffer.name, line, column,
                              params)
+ # disable completions for now:
+ # https://github.com/Rip-Rip/clang_complete/issues/446
+   return (str([]), timer)

    t = CompleteThread(line, column, getCurrentFile(), vim.current.buffer.name,
                       params, timer)`

This is better than removing the plugin altogether since syntax checking on save still works fine.

**Comment by thecloudexpanse** [comment]
OK. After reading [issue 452](https://github.com/Rip-Rip/clang_complete/issues/452), I took another look at my installed vim plugins. I have never installed YouCompleteMe so knew that wasn't an issue, but I did have Syntastic 3.5.0 installed. So I removed Syntastic, as well as the early return that I added to libclang.py in my previous comment, and now completions are working fine. No SEGVs with any of the files that used to reproduce the problem every time.

It seems like you can't have two plugins installed that act on completions, or it will trigger the Python threading issue. Ugh. Apparently Syntastic was actually handling the syntax check on file save, and that's a pretty useful feature to give up. Will look further to see if there's a way to just disable its handling of code completions.

My relevant .vimrc settings:
```
function ClangLibPath()
    let clangPath = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/'
    return clangPath
endfunction
let g:clang_user_options='|| exit 0'
let g:clang_complete_auto = 1
let g:clang_complete_copen = 0
let g:clang_library_path=ClangLibPath()
```

**Comment by iiey** [comment]
I doubt it has conflict with other plugins but the problem of clang_complete itself because I don't use ycm and currently don't have syntastic too

my vimrc has no special configuration for clang_complete except using ultisnip as snippets engine
`let g:clang_snippets_engine = 'ultisnips'`

**Comment by wilywampa** [comment]
I've gotten the SEGV using `ClangGotoDeclaration`, so it's not limited to completion.
