### ISSUE TITLE
NameError: name 'initClangComplete' is not defined

### ISSUE THREAD

**Issue by JackieTseng** [Rip-Rip/clang_complete#476]
```
Error detected while processing function <SNR>35_ClangCompleteInit..<SNR>35_initClangCompletePython:
line 13:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jackie/.vim/bundle/clang_complete/plugin/libclang.py", line 1, in <module>
    from clang.cindex import *
  File "/home/jackie/.vim/bundle/clang_complete/plugin/clang/cindex.py", line 65, in <module>
    from ctypes import *
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
line 29:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'initClangComplete' is not defined
line 30:
E121: Undefined variable: l:res
E15: Invalid expression: l:res == 0
line 35:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'WarmupCache' is not defined
```

I am suffering form this problem. And I tried so many methods online which doesn't work to me.
My Vim version is 7.4.52.
      libclang-dev is the latest.
      clang-complete is the latest.
Anyone who can helps, thanks a lot.

Ps. I found if I use [sudo] vim to open file, there will no error appear.

**Comment by xaizek** [comment]
> ImportError: No module named _ctypes

Looks like your python is broken, this shouldn't yield errors:
```
$ python
Python 2.7.11 (default, Dec  6 2015, 14:10:30) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
@>>> import ctypes
```
but you probably will get one. If python doesn't work, this plugin won't work either.

**Comment by JackieTseng** [comment]
@xaizek This is what my terminal show,

`Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ctypes
>>> 
`
No error occur. What should I do next?

**Comment by xaizek** [comment]
`_ctypes` works too? Maybe some modules are installed into root home or there are issues with file permissions. Or this is not the python Vim is trying to use, or it is used incorrectly. Or module search path is wrong (I think there was an environment variable for this).

**Comment by JackieTseng** [comment]
@xaizek _ctypes works too. I have doubted that there are some issues which should be access by `sudo`. However I can't find. What can I do now? Or which part should I reinstall for solving this strange problem? I have tried reinstall the vim, libclang-dev and clang-complete plugin. Nor works.

**Comment by xaizek** [comment]
Check that `$PYTHONPATH` isn't set and try whether `:python import _ctypes` works in Vim.

**Comment by JackieTseng** [comment]
@xaizek I found that my `$PYTHONPATH` have been set. Then I set `/usr/lib/python3.4` which cause the problem like `http://stackoverflow.com/questions/7888222/subprocess-module-fails-to-run-command`. As a result, I change into `/usr/lib/python2.7`. However the original problem still exist when I open any C++ file as following:
```
Error detected while processing function <SNR>35_ClangCompleteInit..<SNR>35_initClangCompletePython:
line 13:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jackie/.vim/bundle/clang_complete/plugin/libclang.py", line 1, in <module>
    from clang.cindex import *
  File "/home/jackie/.vim/bundle/clang_complete/plugin/clang/cindex.py", line 65, in <module>
    from ctypes import *
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
line 29:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'initClangComplete' is not defined
line 30:
E121: Undefined variable: l:res
E15: Invalid expression: l:res == 0
line 35:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'WarmupCache' is not defined
```

**Comment by xaizek** [comment]
`_ctypes` seems to be builtin module, maybe your Vim uses python3 and this is python2 module? One of the forks contains changes for python3 I think. What's the output of `vim --version | grep python`?

**Comment by JackieTseng** [comment]
@xaizek The output is 
```
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
链接方式: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```
Is there any problem?

**Comment by xaizek** [comment]
Looks like it should use python2, so it should work... Don't really know why error appears then.

**Comment by JackieTseng** [comment]
@xaizek Sad, I don't know either. It seems it can't be fixed unless I reinstall ubuntu. Thanks you all the same.
