### ISSUE TITLE
User defined completion (^U^N^P) Pattern not found error

### ISSUE THREAD

**Issue by qiuzhiqian** [Rip-Rip/clang_complete#529]
in my c code the clang_complete cannot work.Vim show error message: 'User defined completion (^U^N^P) Pattern not found' after . or ->.
when i run ::call g:ClangUpdateQuickFix(),vim return

Error detected while processing function ClangUpdateQuickFix[1]..<SNR>12_DoPeriodicQuickFix:                       
line    7:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'updateCurrentDiagnostics' is not defined
Error detected while processing function ClangUpdateQuickFix[1]..<SNR>12_DoPeriodicQuickFix[8]..<SNR>12_ClangQuickFix:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'highlightCurrentDiagnostics' is not defined
line    8:
E121: Undefined variable: g:clang_complete_copen
E15: Invalid expression: g:clang_complete_copen == 1
line   23:
E121: Undefined variable: l:list
E116: Invalid arguments for function setqflist

**Comment by talih0** [comment]
Check if vim has been compiled with python support: 
either 
:echo has('python') 
or 
:echo has('python3')
**should return 1.** 
If both are 0, then you need to reinstall vim with python support. See https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
Pay careful attention to  --with-python-config-dir when running ./configure. Make sure the directory for python exists. 
**Compile only with python2 or python3, but not both**. I've had issues setting both flags in the past.
